In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/manojbamniya/netflix-titles/netflix_titles.csv

In [2]:
df = pd.read_csv('/kaggle/input/datasets/manojbamniya/netflix-titles/netflix_titles.csv')

In [3]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [4]:
df.shape

(6234, 12)

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
# 1. Count the duplicate titles
duplicate_count = df['title'].duplicated().sum()
print(f"Total duplicate titles found: {duplicate_count}\n")

# 2. View ALL rows that share a duplicate title (ordered by title)
duplicate_rows = df[df.duplicated(subset=['title'], keep=False)].sort_values(by='title')
duplicate_rows.head()

Total duplicate titles found: 62

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5905,80026224,TV Show,Aquarius,NaN,"David Duchovny, Gethin Anthony, Grey Damon, Em...",United States,"June 16, 2017",2016,TV-MA,2 Seasons,"Crime TV Shows, TV Dramas","Amid the turmoil of 1960s LA, two cops and a p..."
3441,80113667,Movie,Aquarius,Kleber Mendonça Filho,"Sonia Braga, Maeve Jinkings, Irandhir Santos, ...","Brazil, France","January 13, 2017",2016,UR,146 min,"Dramas, International Movies",The final holdout in her historic beachside bu...
2159,80204923,Movie,Benji,Brandon Camp,"Gabriel Bateman, Darby Camp, Kiele Sanchez, Je...","United Arab Emirates, United States","March 16, 2018",2018,TV-PG,87 min,"Children & Family Movies, Dramas",A determined dog comes to the rescue and helps...
1969,296682,Movie,Benji,Joe Camp,"Benji, Deborah Walley, Peter Breck, Edgar Buch...",United States,"March 6, 2018",1974,G,86 min,"Children & Family Movies, Classic Movies",After lovable abandoned mutt Benji is adopted ...
5724,70204957,TV Show,Bleach,NaN,"Masakazu Morita, Fumiko Orikasa, Yuki Matsuoka...",Japan,"November 3, 2018",2006,TV-14,3 Seasons,"Anime Series, International TV Shows",After teenager Ichigo Kurosaki acquires superp...

In [7]:
df.isnull().sum()

show_id            0
type               0
title              0
director        1969
cast             570
country          476
date_added        11
release_year       0
rating            10
duration           0
listed_in          0
description        0
dtype: int64

In [8]:
cols = [c for c in df.columns if c != "show_id"]
dupes = df[df.duplicated(subset=cols, keep=False)]
print(dupes[["show_id", "title", "release_year"]])

       show_id   title  release_year
2123  81075235  Sarkar          2018
2124  81072516  Sarkar          2018

In [9]:
# 1. Drop the duplicate row
df = df.drop(2124)

# 2. Reset the row numbers so there are no missing gaps
df = df.reset_index(drop=True)

In [10]:
null_rows = df[df.isnull().any(axis=1)]

In [11]:
null_rows

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
5,80163890,TV Show,Apaches,NaN,"Alberto Ammann, Eloy Azorín, Verónica Echegui,...",Spain,"September 8, 2017",2016,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...",A young journalist is forced into a life of cr...
8,80117902,TV Show,Fire Chasers,NaN,NaN,United States,"September 8, 2017",2017,TV-MA,1 Season,"Docuseries, Science & Nature TV","As California's 2016 fire season rages, brave ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
6228,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6229,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6230,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...
6231,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6232,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [12]:
df['description'].isnull().sum()

np.int64(0)

In [13]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

**filter shows by country, year, type, rating.**

In [14]:
country_null_rows = df[df['country'].isnull()]
country_null_rows

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
10,80169755,Movie,Joaquín Reyes: Una y no más,José Miguel Contreras,Joaquín Reyes,NaN,"September 8, 2017",2017,TV-MA,78 min,Stand-Up Comedy,Comedian and celebrity impersonator Joaquín Re...
12,80182480,Movie,Krish Trish and Baltiboy,NaN,"Damandeep Singh Baggan, Smita Malhotra, Baba S...",NaN,"September 8, 2017",2009,TV-Y7,58 min,Children & Family Movies,"A team of minstrels, including a monkey, cat a..."
13,80182483,Movie,Krish Trish and Baltiboy: Battle of Wits,"Munjal Shroff, Tilak Shetty","Damandeep Singh Baggan, Smita Malhotra, Baba S...",NaN,"September 8, 2017",2013,TV-Y7,62 min,Children & Family Movies,"An artisan is cheated of his payment, a lion o..."
14,80182596,Movie,Krish Trish and Baltiboy: Best Friends Forever,"Munjal Shroff, Tilak Shetty","Damandeep Singh Baggan, Smita Malhotra, Deepak...",NaN,"September 8, 2017",2016,TV-Y,65 min,Children & Family Movies,"A cat, monkey and donkey team up to narrate fo..."
15,80182482,Movie,Krish Trish and Baltiboy: Comics of India,Tilak Shetty,"Damandeep Singh Baggan, Smita Malhotra, Baba S...",NaN,"September 8, 2017",2012,TV-Y7,61 min,Children & Family Movies,"In three comic-strip-style tales, a boy tries ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
6169,80136456,TV Show,Age of Glory,NaN,"Debbie Goh, Aenie Wong, Frederick Lee, Leslie ...",NaN,"August 14, 2017",2010,TV-PG,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",Amid the thriving nightlife of 1960s Kuala Lum...
6194,80136790,TV Show,Goodnight DJ 1,NaN,"Chan Fong, Z-Chen, Frederick Lee, Melvin Sia, ...",NaN,"April 27, 2018",2016,TV-14,2 Seasons,"International TV Shows, TV Dramas, TV Horror",Young radio announcers from varying background...
6198,80244228,TV Show,Beauty and the Bitches,NaN,"Methinee Kingpayome, Son Songpaisarn, Yingying...",NaN,"April 23, 2019",2016,TV-14,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",Beauty pageant contestants from all over Thail...
6227,80159925,TV Show,Kikoriki,NaN,Igor Dmitriev,NaN,NaN,2010,TV-Y,2 Seasons,Kids' TV,A wacky rabbit and his gang of animal pals hav...
6230,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...

In [15]:
# 1. Count NaNs per row and filter for rows with more than 2
nan_rows = df[df.isnull().sum(axis=1) > 2]
nan_rows

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
28,80190843,TV Show,First and Last,NaN,NaN,NaN,"September 7, 2018",2018,TV-MA,1 Season,Docuseries,Take an intimate look at the emotionally charg...
147,80195173,TV Show,Battlefish,NaN,NaN,NaN,"September 21, 2018",2018,TV-MA,1 Season,"Reality TV, Science & Nature TV, TV Action & A...","Over the course of a fishing season, tough men..."
174,80128096,TV Show,Chef's Table: France,NaN,NaN,NaN,"September 2, 2016",2016,TV-14,1 Season,Docuseries,Sample the bold new flavors of France with che...
233,80241103,TV Show,How to Live Mortgage Free with Sarah Beeny,NaN,NaN,NaN,"September 15, 2018",2018,TV-14,1 Season,"British TV Shows, International TV Shows, Real...",Real estate expert and TV presenter Sarah Been...
258,80220035,TV Show,Boca Juniors Confidential,NaN,NaN,NaN,"September 14, 2018",2018,TV-PG,1 Season,"Docuseries, International TV Shows, Spanish-La...","Players, fans and staff of soccer powerhouse B..."
307,81073764,TV Show,Loo Loo Kids: Johny & Friends Musical Adventures,NaN,NaN,NaN,"September 1, 2019",2016,TV-Y,1 Season,Kids' TV,Music-loving baby Johny goes on dance-filled a...
359,80203742,Movie,"Alias JJ, la celebridad del mal",NaN,NaN,NaN,"September 1, 2017",2017,TV-14,54 min,"Documentaries, International Movies",Witnesses and public figures respond to contro...
595,80224490,TV Show,Diva Brides,NaN,NaN,NaN,"October 2, 2019",2017,TV-MA,1 Season,"British TV Shows, Reality TV","In this reality series, brides-to-be stop at n..."
687,81154549,TV Show,Magical Andes,NaN,NaN,NaN,"October 15, 2019",2019,TV-G,1 Season,"Docuseries, International TV Shows, Science & ...","From Argentina to Colombia, this stunning docu..."
735,80180544,TV Show,Ajaibnya Cinta,NaN,NaN,NaN,"October 13, 2017",2015,TV-PG,1 Season,"International TV Shows, TV Dramas","Upon returning home from his studies abroad, y..."
808,81179400,Movie,Little Baby Bum: Go Buster,NaN,NaN,NaN,"October 1, 2019",2019,TV-Y,58 min,Children & Family Movies,This compilation for preschoolers features a p...
1198,81039045,TV Show,Paap-O-Meter,NaN,NaN,NaN,"November 20, 2018",2017,TV-Y7,1 Season,"Kids' TV, TV Comedies",A trio of sky-dwelling ghosts must travel to E...
1605,80217946,TV Show,Killer Ratings,NaN,NaN,NaN,"May 31, 2019",2019,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...",Brazilian TV personality and politician Wallac...
1803,80216756,TV Show,Jailbirds,NaN,NaN,NaN,"May 10, 2019",2019,TV-MA,1 Season,Reality TV,"At the Sacramento County Jail, incarcerated wo..."
1864,80229190,TV Show,Queens of Comedy,NaN,NaN,NaN,"May 1, 2018",2017,TV-MA,1 Season,"International TV Shows, Stand-Up Comedy & Talk...",Eight women perform in front of celebrity judg...
1995,80232149,TV Show,"Bure Kaam Bura Natija, Kyun Bhai Chacha Haan B...",NaN,NaN,NaN,"March 31, 2018",2017,TV-Y7,1 Season,Kids' TV,"A clever uncle-nephew duo solves mysteries, cr..."
2094,80223108,TV Show,Selling Sunset,NaN,NaN,NaN,"March 22, 2019",2019,TV-MA,1 Season,Reality TV,The elite real estate brokers at The Oppenheim...
2098,81049949,Movie,Antoine Griezmann: The Making of a Legend,NaN,NaN,NaN,"March 21, 2019",2019,TV-PG,60 min,"Documentaries, International Movies, Sports Mo...","With heart and determination, Antoine Griezman..."
2186,80194956,TV Show,The Disappearance of Madeleine McCann,NaN,NaN,NaN,"March 15, 2019",2019,TV-14,1 Season,"Crime TV Shows, Docuseries",The documentary takes a detailed look at the d...
2305,80198306,TV Show,Losers,NaN,NaN,NaN,"March 1, 2019",2019,TV-MA,1 Season,Docuseries,"In a ""winning is everything"" society, how do w..."
2575,80993087,TV Show,Melodies of Life - Born This Way,NaN,NaN,NaN,"June 21, 2019",2016,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",A celebrated pastry chef and his fellow staff ...
3013,80224602,TV Show,Money for Nothing,NaN,NaN,NaN,"July 12, 2019",2015,TV-PG,1 Season,"British TV Shows, International TV Shows, Real...","Aided by designers and craftspeople, entrepren..."
3287,80169801,Movie,13TH: A Conversation with Oprah Winfrey & Ava ...,NaN,"Oprah Winfrey, Ava DuVernay",NaN,"January 26, 2017",2017,NaN,37 min,Movies,Oprah Winfrey sits down with director Ava DuVe...
3346,81038583,TV Show,Strongland,NaN,NaN,NaN,"January 18, 2019",2018,TV-PG,1 Season,"Docuseries, International TV Shows",From Spain's countryside to Scotland's stony t...
3457,80210995,TV Show,Back with the Ex,NaN,NaN,NaN,"January 11, 2019",2018,TV-MA,1 Season,"International TV Shows, Reality TV, Romantic T...",New beginnings or old baggage? Four singles ha...
3927,80184154,TV Show,Kon Kon Kon,NaN,NaN,NaN,"February 16, 2018",2014,TV-PG,1 Season,"Docuseries, International TV Shows",Explore the stories of ordinary people dealing...
3980,80204889,TV Show,Dating Around,NaN,NaN,NaN,"February 14, 2019",2019,TV-MA,1 Season,"Reality TV, Romantic TV Shows","In each episode of flirtations and fails, one ..."
4082,80093829,TV Show,Masha's Tales,NaN,NaN,NaN,"February 1, 2016",2012,TV-Y,1 Season,Kids' TV,Fairy tales get a funny twist when Masha retel...
4291,81030762,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-PG,1 Season,TV Shows,This collection restores films from women who ...
4334,80204885,TV Show,Towies,NaN,NaN,NaN,"December 27, 2017",2016,TV-MA,1 Season,"International TV Shows, Reality TV",Australia's toughest tow truck operators work ...
4401,80092839,Movie,Fireplace 4K: Classic Crackling Fireplace from...,George Ford,NaN,NaN,"December 21, 2015",2015,NaN,60 min,Movies,"The first of its kind in UHD 4K, with the clea..."
4402,80092835,Movie,Fireplace 4K: Crackling Birchwood from Firepla...,George Ford,NaN,NaN,"December 21, 2015",2015,NaN,60 min,Movies,"For the first time in 4K Ultra-HD, everyone's ..."
4516,81034632,Movie,Once in a Lifetime Sessions with George Ezra,NaN,NaN,NaN,"December 15, 2018",2018,TV-14,78 min,"Documentaries, Music & Musicals",English singer-songwriter George Ezra performs...
4518,81034634,Movie,Once in a Lifetime Sessions with OneRepublic,NaN,NaN,NaN,"December 15, 2018",2018,TV-PG,73 min,"Documentaries, Music & Musicals","Exclusive interviews, live performances and st..."
4637,80202859,TV Show,The Bachelor,NaN,NaN,NaN,"December 1, 2019",2009,TV-14,1 Season,"Reality TV, Romantic TV Shows",A single man searches for his soulmate through...
4768,81035838,Movie,Alarmoty in the Land of Fire,NaN,NaN,NaN,"August 5, 2019",2017,TV-14,94 min,"Comedies, International Movies","While vacationing at a resort, an ornery and o..."
5000,81014293,TV Show,Nuestra Lucha Libre,NaN,NaN,NaN,"August 15, 2018",2018,TV-MA,1 Season,"Docuseries, International TV Shows, Spanish-La...",This documentary series lifts the mask on Mexi...
5001,81014811,TV Show,The Creative Indians,NaN,NaN,NaN,"August 15, 2018",2017,NR,1 Season,"Docuseries, International TV Shows",From chefs and comedians to filmmakers and fas...
5017,80223113,TV Show,Happy Jail,NaN,NaN,NaN,"August 14, 2019",2019,TV-MA,1 Season,"Crime TV Shows, Docuseries",The Philippine jail known for a viral Michael ...
5272,80136793,TV Show,Dancing Angels,NaN,NaN,NaN,"April 27, 2018",2016,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...",A group of aspiring young musicians yearn for ...
5477,81072430,TV Show,JingleKids,NaN,NaN,NaN,"April 1, 2019",2017,TV-Y7,1 Season,Kids' TV,"In a magical wonderland, merry children and th..."
5478,81039073,TV Show,Kicko & Super Speedo,NaN,NaN,NaN,"April 1, 2019",2018,TV-Y7-FV,1 Season,"Kids' TV, TV Comedies",This high-energy animated series follows a gut...
5659,81192130,TV Show,"ChuChu TV Kids Songs, Learning Videos & Bedtim...",NaN,NaN,NaN,"October 25, 2019",2019,TV-Y,2 Seasons,Kids' TV,This educational series for tiny tots features...
5972,81100135,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
6140,80211492,TV Show,Mighty Little Bheem,NaN,NaN,NaN,"August 30, 2019",2019,TV-Y,2 Seasons,"Kids' TV, TV Comedies",An innocent toddler’s boundless curiosity – an...
6227,80159925,TV Show,Kikoriki,NaN,Igor Dmitriev,NaN,NaN,2010,TV-Y,2 Seasons,Kids' TV,A wacky rabbit and his gang of animal pals hav...
6230,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...

In [16]:
nan_rows.shape

(47, 12)

**here two question come into my mind** 
1. should i drop the rows who has more than 2 columns na1. or
2. i can search from the internet with the ai model and fill this rows.
* i can go both ways firstly i am going with the droping the rows who has more than 2 nan

In [17]:
# Drops the rows AND resets the row numbers back to 0, 1, 2, 3...
df1 = df.drop(df[df.isnull().sum(axis=1) > 2].index).reset_index(drop=True)

In [18]:
df1.shape

(6186, 12)

In [19]:
df.shape

(6233, 12)

In [20]:
df1.isnull().sum()

show_id            0
type               0
title              0
director        1924
cast             525
country          429
date_added         9
release_year       0
rating             6
duration           0
listed_in          0
description        0
dtype: int64

In [21]:
# 1. Remove the text width limit completely
pd.set_option('display.max_colwidth', None)

In [22]:
df1['description'].head(1)

0    Before planning an awesome wedding for his grandfather, a polar bear king must take back a stolen artifact from an evil archaeologist first.
Name: description, dtype: object

In [23]:
df1 = df1.dropna(subset=['rating']).reset_index(drop=True)

In [24]:
df1.isnull().sum()

show_id            0
type               0
title              0
director        1922
cast             525
country          429
date_added         9
release_year       0
rating             0
duration           0
listed_in          0
description        0
dtype: int64

In [25]:
df1.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [26]:
df1.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole Howard, Jennifer Cameron, Jonathan Holmes, Lee Tockar, Lisa Durupt, Maya Kay, Michael Dobson","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies","Before planning an awesome wedding for his grandfather, a polar bear king must take back a stolen artifact from an evil archaeologist first."
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,"Jandino Asporaat riffs on the challenges of raising kids and serenades the audience with a rousing rendition of ""Sex on Fire"" in his comedy show."
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, Jeffrey Combs, Kevin Michael Richardson, Tania Gunadi, Josh Keaton, Steve Blum, Andy Pessoa, Ernie Hudson, Daran Norris, Will Friedle",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autobots once again protect Earth from the onslaught of the Decepticons and their leader, Megatron."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, Khary Payton, Mitchell Whitfield, Stuart Allan, Ted McGinley, Peter Cullen",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,"When a prison ship crash unleashes hundreds of Decepticons on Earth, Bumblebee leads a new Autobot force to protect humankind."
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins, Keith Powers, Alicia Sanz, Jake Borelli, Kid Ink, Yousef Erakat, Rebekah Graf, Anne Winters, Peter Gilroy, Patrick Davis",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,"When nerdy high schooler Dani finally attracts the interest of her longtime crush, she lands in the cross hairs of his ex, a social media celebrity."

In [27]:
# Rename a column and save it to a new DataFrame
df1 = df1.rename(columns={'release_year': 'year'})

In [28]:
df1.head()

,show_id,type,title,director,cast,country,date_added,year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole Howard, Jennifer Cameron, Jonathan Holmes, Lee Tockar, Lisa Durupt, Maya Kay, Michael Dobson","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies","Before planning an awesome wedding for his grandfather, a polar bear king must take back a stolen artifact from an evil archaeologist first."
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,"Jandino Asporaat riffs on the challenges of raising kids and serenades the audience with a rousing rendition of ""Sex on Fire"" in his comedy show."
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, Jeffrey Combs, Kevin Michael Richardson, Tania Gunadi, Josh Keaton, Steve Blum, Andy Pessoa, Ernie Hudson, Daran Norris, Will Friedle",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autobots once again protect Earth from the onslaught of the Decepticons and their leader, Megatron."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, Khary Payton, Mitchell Whitfield, Stuart Allan, Ted McGinley, Peter Cullen",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,"When a prison ship crash unleashes hundreds of Decepticons on Earth, Bumblebee leads a new Autobot force to protect humankind."
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins, Keith Powers, Alicia Sanz, Jake Borelli, Kid Ink, Yousef Erakat, Rebekah Graf, Anne Winters, Peter Gilroy, Patrick Davis",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,"When nerdy high schooler Dani finally attracts the interest of her longtime crush, she lands in the cross hairs of his ex, a social media celebrity."

In [29]:
# Replace NaN with "" in the 'description' column and save it back
df1['director'] = df1['director'].fillna("")

In [30]:
df1['cast'] = df1['cast'].fillna("")

In [31]:
df1.isnull().sum()

show_id          0
type             0
title            0
director         0
cast             0
country        429
date_added       9
year             0
rating           0
duration         0
listed_in        0
description      0
dtype: int64

In [32]:
# Create an independent copy named movies
movies = df1.copy()

In [33]:
movies.head()

,show_id,type,title,director,cast,country,date_added,year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole Howard, Jennifer Cameron, Jonathan Holmes, Lee Tockar, Lisa Durupt, Maya Kay, Michael Dobson","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies","Before planning an awesome wedding for his grandfather, a polar bear king must take back a stolen artifact from an evil archaeologist first."
1,80117401,Movie,Jandino: Whatever it Takes,,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,"Jandino Asporaat riffs on the challenges of raising kids and serenades the audience with a rousing rendition of ""Sex on Fire"" in his comedy show."
2,70234439,TV Show,Transformers Prime,,"Peter Cullen, Sumalee Montano, Frank Welker, Jeffrey Combs, Kevin Michael Richardson, Tania Gunadi, Josh Keaton, Steve Blum, Andy Pessoa, Ernie Hudson, Daran Norris, Will Friedle",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autobots once again protect Earth from the onslaught of the Decepticons and their leader, Megatron."
3,80058654,TV Show,Transformers: Robots in Disguise,,"Will Friedle, Darren Criss, Constance Zimmer, Khary Payton, Mitchell Whitfield, Stuart Allan, Ted McGinley, Peter Cullen",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,"When a prison ship crash unleashes hundreds of Decepticons on Earth, Bumblebee leads a new Autobot force to protect humankind."
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins, Keith Powers, Alicia Sanz, Jake Borelli, Kid Ink, Yousef Erakat, Rebekah Graf, Anne Winters, Peter Gilroy, Patrick Davis",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,"When nerdy high schooler Dani finally attracts the interest of her longtime crush, she lands in the cross hairs of his ex, a social media celebrity."

i want country column to be seperated so i can't replace it with empty string

In [34]:
movies.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [35]:
def describe_and_combine(row):
    """
    Combines description, genres, duration, cast, and director into one string.
    Adds labels (Genres:, Duration:, etc.) and handles both text strings and lists.
    Skips missing data, empty strings, or empty lists completely.
    """
    parts = []
    
    # 1. Add description if it exists
    if pd.notna(row['description']) and str(row['description']).strip():
        parts.append(str(row['description']).strip())
        
    # 2. Add columns with their labels sequentially
    columns_to_check = [
        ("listed_in", "Genres"), 
        ("duration", "Duration"),
        ("cast", "Cast"), 
        ("director", "Director")
    ]
    
    for column, label in columns_to_check:
        val = row[column]
        
        if pd.notna(val):
            # If it's a list (and has items), join them with commas
            if isinstance(val, list) and len(val) > 0:
                list_as_str = ", ".join(map(str, val))
                parts.append(f"{label}: {list_as_str}.")
            
            # If it's a regular string (and not empty spaces), append it
            elif isinstance(val, str) and val.strip():
                parts.append(f"{label}: {val.strip()}.")
                
    # Combine everything with spaces
    combined_text = " ".join(parts)
    
    # Optional Cleanup: Remove any double spaces or isolated trailing commas from lists
    cleaned_words = [word.strip(',') for word in combined_text.split() if word.strip(',') != '']
    
    return " ".join(cleaned_words)

# Apply it to your DataFrame (make sure your variable name matches 'movies' or 'df')
movies['movie_description'] = movies.apply(describe_and_combine, axis=1)

In [36]:
movies.head()

,show_id,type,title,director,cast,country,date_added,year,rating,duration,listed_in,description,movie_description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole Howard, Jennifer Cameron, Jonathan Holmes, Lee Tockar, Lisa Durupt, Maya Kay, Michael Dobson","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies","Before planning an awesome wedding for his grandfather, a polar bear king must take back a stolen artifact from an evil archaeologist first.",Before planning an awesome wedding for his grandfather a polar bear king must take back a stolen artifact from an evil archaeologist first. Genres: Children & Family Movies Comedies. Duration: 90 min. Cast: Alan Marriott Andrew Toth Brian Dobson Cole Howard Jennifer Cameron Jonathan Holmes Lee Tockar Lisa Durupt Maya Kay Michael Dobson. Director: Richard Finn Tim Maltby.
1,80117401,Movie,Jandino: Whatever it Takes,,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,"Jandino Asporaat riffs on the challenges of raising kids and serenades the audience with a rousing rendition of ""Sex on Fire"" in his comedy show.","Jandino Asporaat riffs on the challenges of raising kids and serenades the audience with a rousing rendition of ""Sex on Fire"" in his comedy show. Genres: Stand-Up Comedy. Duration: 94 min. Cast: Jandino Asporaat."
2,70234439,TV Show,Transformers Prime,,"Peter Cullen, Sumalee Montano, Frank Welker, Jeffrey Combs, Kevin Michael Richardson, Tania Gunadi, Josh Keaton, Steve Blum, Andy Pessoa, Ernie Hudson, Daran Norris, Will Friedle",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autobots once again protect Earth from the onslaught of the Decepticons and their leader, Megatron.",With the help of three human allies the Autobots once again protect Earth from the onslaught of the Decepticons and their leader Megatron. Genres: Kids' TV. Duration: 1 Season. Cast: Peter Cullen Sumalee Montano Frank Welker Jeffrey Combs Kevin Michael Richardson Tania Gunadi Josh Keaton Steve Blum Andy Pessoa Ernie Hudson Daran Norris Will Friedle.
3,80058654,TV Show,Transformers: Robots in Disguise,,"Will Friedle, Darren Criss, Constance Zimmer, Khary Payton, Mitchell Whitfield, Stuart Allan, Ted McGinley, Peter Cullen",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,"When a prison ship crash unleashes hundreds of Decepticons on Earth, Bumblebee leads a new Autobot force to protect humankind.",When a prison ship crash unleashes hundreds of Decepticons on Earth Bumblebee leads a new Autobot force to protect humankind. Genres: Kids' TV. Duration: 1 Season. Cast: Will Friedle Darren Criss Constance Zimmer Khary Payton Mitchell Whitfield Stuart Allan Ted McGinley Peter Cullen.
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins, Keith Powers, Alicia Sanz, Jake Borelli, Kid Ink, Yousef Erakat, Rebekah Graf, Anne Winters, Peter Gilroy, Patrick Davis",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,"When nerdy high schooler Dani finally attracts the interest of her longtime crush, she lands in the cross hairs of his ex, a social media celebrity.",When nerdy high schooler Dani finally attracts the interest of her longtime crush she lands in the cross hairs of his ex a social media celebrity. Genres: Comedies. Duration: 99 min. Cast: Nesta Cooper Kate Walsh John Michael Higgins Keith Powers Alicia Sanz Jake Borelli Kid Ink Yousef Erakat Rebekah Graf Anne Winters Peter Gilroy Patrick Davis. Director: Fernando Lebrija.

In [37]:
movies.head(3)

,show_id,type,title,director,cast,country,date_added,year,rating,duration,listed_in,description,movie_description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole Howard, Jennifer Cameron, Jonathan Holmes, Lee Tockar, Lisa Durupt, Maya Kay, Michael Dobson","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies","Before planning an awesome wedding for his grandfather, a polar bear king must take back a stolen artifact from an evil archaeologist first.",Before planning an awesome wedding for his grandfather a polar bear king must take back a stolen artifact from an evil archaeologist first. Genres: Children & Family Movies Comedies. Duration: 90 min. Cast: Alan Marriott Andrew Toth Brian Dobson Cole Howard Jennifer Cameron Jonathan Holmes Lee Tockar Lisa Durupt Maya Kay Michael Dobson. Director: Richard Finn Tim Maltby.
1,80117401,Movie,Jandino: Whatever it Takes,,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,"Jandino Asporaat riffs on the challenges of raising kids and serenades the audience with a rousing rendition of ""Sex on Fire"" in his comedy show.","Jandino Asporaat riffs on the challenges of raising kids and serenades the audience with a rousing rendition of ""Sex on Fire"" in his comedy show. Genres: Stand-Up Comedy. Duration: 94 min. Cast: Jandino Asporaat."
2,70234439,TV Show,Transformers Prime,,"Peter Cullen, Sumalee Montano, Frank Welker, Jeffrey Combs, Kevin Michael Richardson, Tania Gunadi, Josh Keaton, Steve Blum, Andy Pessoa, Ernie Hudson, Daran Norris, Will Friedle",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autobots once again protect Earth from the onslaught of the Decepticons and their leader, Megatron.",With the help of three human allies the Autobots once again protect Earth from the onslaught of the Decepticons and their leader Megatron. Genres: Kids' TV. Duration: 1 Season. Cast: Peter Cullen Sumalee Montano Frank Welker Jeffrey Combs Kevin Michael Richardson Tania Gunadi Josh Keaton Steve Blum Andy Pessoa Ernie Hudson Daran Norris Will Friedle.

In [38]:
movies = movies.drop(columns=['director','cast','duration','listed_in','description'])

In [39]:
movies

,show_id,type,title,country,date_added,year,rating,movie_description
0,81145628,Movie,Norm of the North: King Sized Adventure,"United States, India, South Korea, China","September 9, 2019",2019,TV-PG,Before planning an awesome wedding for his grandfather a polar bear king must take back a stolen artifact from an evil archaeologist first. Genres: Children & Family Movies Comedies. Duration: 90 min. Cast: Alan Marriott Andrew Toth Brian Dobson Cole Howard Jennifer Cameron Jonathan Holmes Lee Tockar Lisa Durupt Maya Kay Michael Dobson. Director: Richard Finn Tim Maltby.
1,80117401,Movie,Jandino: Whatever it Takes,United Kingdom,"September 9, 2016",2016,TV-MA,"Jandino Asporaat riffs on the challenges of raising kids and serenades the audience with a rousing rendition of ""Sex on Fire"" in his comedy show. Genres: Stand-Up Comedy. Duration: 94 min. Cast: Jandino Asporaat."
2,70234439,TV Show,Transformers Prime,United States,"September 8, 2018",2013,TV-Y7-FV,With the help of three human allies the Autobots once again protect Earth from the onslaught of the Decepticons and their leader Megatron. Genres: Kids' TV. Duration: 1 Season. Cast: Peter Cullen Sumalee Montano Frank Welker Jeffrey Combs Kevin Michael Richardson Tania Gunadi Josh Keaton Steve Blum Andy Pessoa Ernie Hudson Daran Norris Will Friedle.
3,80058654,TV Show,Transformers: Robots in Disguise,United States,"September 8, 2018",2016,TV-Y7,When a prison ship crash unleashes hundreds of Decepticons on Earth Bumblebee leads a new Autobot force to protect humankind. Genres: Kids' TV. Duration: 1 Season. Cast: Will Friedle Darren Criss Constance Zimmer Khary Payton Mitchell Whitfield Stuart Allan Ted McGinley Peter Cullen.
4,80125979,Movie,#realityhigh,United States,"September 8, 2017",2017,TV-14,When nerdy high schooler Dani finally attracts the interest of her longtime crush she lands in the cross hairs of his ex a social media celebrity. Genres: Comedies. Duration: 99 min. Cast: Nesta Cooper Kate Walsh John Michael Higgins Keith Powers Alicia Sanz Jake Borelli Kid Ink Yousef Erakat Rebekah Graf Anne Winters Peter Gilroy Patrick Davis. Director: Fernando Lebrija.
...,...,...,...,...,...,...,...,...
6175,80005756,TV Show,The Adventures of Figaro Pho,Australia,NaN,2015,TV-Y7,Imagine your worst fears then multiply them: Figaro is a boy with any number of phobias and a highly quirky and imaginative way of dealing with them. Genres: Kids' TV TV Comedies. Duration: 2 Seasons. Cast: Luke Jurevicius Craig Behenna Charlotte Hamlyn Stavroula Mountzouris Aletheia Burney.
6176,80000063,TV Show,Red vs. Blue,United States,NaN,2015,NR,This parody of first-person shooter games military life and science-fiction films centers on a civil war fought in the middle of a desolate canyon. Genres: TV Action & Adventure TV Comedies TV Sci-Fi & Fantasy. Duration: 13 Seasons. Cast: Burnie Burns Jason Saldaña Gustavo Sorola Geoff Lazer Ramsey Joel Heyman Matt Hullum Dan Godwin Kathleen Zuelch Yomary Cruz Nathan Zellner.
6177,70286564,TV Show,Maron,United States,NaN,2016,TV-MA,Marc Maron stars as Marc Maron who interviews fellow comedians for his popular podcast only to reveal more about his own neuroses and relationships. Genres: TV Comedies. Duration: 4 Seasons. Cast: Marc Maron Judd Hirsch Josh Brener Nora Zehetner Andy Kindler.
6178,70281022,TV Show,A Young Doctor's Notebook and Other Stories,United Kingdom,NaN,2013,TV-MA,Set during the Russian Revolution this comic miniseries is based on a doctor's memories of his early career working in an out-of-the-way village. Genres: British TV Shows TV Comedies TV Dramas. Duration: 2 Seasons. Cast: Daniel Radcliffe Jon Hamm Adam Godley Christopher Godwin Rosie Cavaliero Vicki Pepperdine Margaret Clunie Tim Steed Shaun Pye.
6179,70153404,TV Show,Friends,United States,NaN,2003,TV-14,This hit sitcom follows the merry misadventures of six 20-something pals as they navigate the pitfalls of work life and love in 1990s Manhattan. Genres: Classic & Cult TV TV Comedies. Duration: 10 Seasons. Cast: Jennifer Aniston Courteney Cox Lisa Kudrow Matt LeBlanc Matthew Perry David Schwimmer.

In [40]:
movies.isnull().sum()

show_id                0
type                   0
title                  0
country              429
date_added             9
year                   0
rating                 0
movie_description      0
dtype: int64

In [41]:
movies.shape

(6180, 8)

In [42]:
# Save your DataFrame as a CSV file
movies.to_csv('netflix_movies.csv', index=False)